### ISSUE TITLE
Adding back Intel support- is it possible?

### ISSUE THREAD

**Issue by RAMChYLD** [vosen/ZLUDA#121]
While I personally use AMD GPUs, I would like to know if it's possible to re-add Intel support back into ZLUDA? The project was recently featured on The Register and interest in getting _any_ non-Nvidia cards working is high. I think it would benefit everyone if both Intel and AMD platforms are supported (as well as the possibility of adding other new platforms, like say Moores Threads cards or even OpenCL support) in the future.

**Comment by vosen** [comment]
I'm closing this as duplicate. Feel free to continue discussion in #85
