### ISSUE TITLE
how to build only libnvcuda?

### ISSUE THREAD

**Issue by SrGabrielBatista** [vosen/ZLUDA#122]
Hello, I only need the libcuda.so for blender and wine apps. Could you show me how to disable the other libs (FFT, BLAS, etc.). I intend to test with rocm 5.7.1 without lib maths and with rocm 5.4.1 with all libs. For an RX580(gfx803).I tried with the available binary, but the segmentation error. tks

**Comment by vosen** [comment]
`cargo build -p zluda_lib --release`
