### ISSUE TITLE
blender中Cycles可以调用amd gpu rx580

### ISSUE THREAD

**Issue by DemoorBug** [vosen/ZLUDA#126]
虽然任务管理器gpu依旧低于10%占用，但是确实比光用cpu快3倍不止大概渲染了40多分钟，如果仅用cpu渲染得3小时多
![屏幕截图 2024-02-21 131635](https://github.com/vosen/ZLUDA/assets/18387615/c013f449-3341-4de6-a81d-8cf1179ce111)

**Comment by DemoorBug** [comment]
一开始输入命令不能使用，重新安装AMD Radeon Software Adrenalin 驱动后就可以用了,并勾选了恢复出厂后设置，驱动版本是24.1.1
模板:`<zluda目录>/zluda.exe -- '<blender完整目录>\blender.exe'`
我自己的用的:
`C:\Users\debug\Desktop\zluda-3-windows\zluda\zluda.exe -- 'C:\Program Files\Blender Foundation\Blender 4.0\blender.exe'`

**Comment by hannnssssssssssssssss** [comment]
我也能在渲染设备中找到zluda，但是渲染不出来东西

**Comment by DemoorBug** [comment]
> 我也能在渲染设备中找到zluda，但是渲染不出来东西

我一开始也是，渲染就会卡住，退出好几次都不行，有一次等了一会，就开始渲染了

**Comment by hannnssssssssssssssss** [comment]
> > 我也能在渲染设备中找到zluda，但是渲染不出来东西
> 
> 我一开始也是，渲染就会卡住，退出好几次都不行，有一次等了一会，就开始渲染了

1

**Comment by hannnssssssssssssssss** [comment]
> > 我也能在渲染设备中找到zluda，但是渲染不出来东西
> 
> 我一开始也是，渲染就会卡住，退出好几次都不行，有一次等了一会，就开始渲染了

看起来它需要等待一段时间才能开始使用，但是它和HIP并没有显著的速度差距，而其它的渲染器看起来是完全不可用的，我在maya的arnold测试过它，没有办法运行起来，有些鸡肋

**Comment by DemoorBug** [comment]
AMD Radeon RX 7900 XTX [ZLUDA] | 4815.82 | 17
AMD Radeon RX 7900 XT [ZLUDA] | 4015.46 | 2
AMD Radeon RX 6800 XT [ZLUDA] | 2612.47 | 1
AMD Radeon RX 7900 XTX | 3935.24 | 325
AMD Radeon RX 7900 XT | 3466.25 | 60
AMD Radeon RX 6800 XT | 2431.06 | 74

这是blender官网的跑分数据
