### ISSUE TITLE
Bark Infinity crashing with ZLUDA (no CUDNN support on windows)

### ISSUE THREAD

**Issue by bykidi** [vosen/ZLUDA#128]
Hi.
Using Bark Infinity from here https://github.com/JonathanFly/bark
GPU is RX 6900 XT
Zluda version 3
When trying to generate audio with bark it crashes with CUDNN_STATUS_INTERNAL_ERROR
Log file https://pastebin.com/xNvncgcy
Installed using their Windows install script

**Comment by lshqqytiger** [comment]
DNN of ZLUDA is available only on Linux.

**Comment by bykidi** [comment]
will we eventually get DNN supported on windows?
or is it some kind of hardware limitation?

**Comment by lshqqytiger** [comment]
AMD MIOpen is an equivalent thing of cuDNN. But it is not included in ROCm 5.7 for Windows.
MIOpen will be available on 6.1 or later. (or you can build it from source yourself)
