### ISSUE TITLE
Why Use Rust？？？？？？？？？！！！！！！！！！！！！

### ISSUE THREAD

**Issue by dayo7116** [vosen/ZLUDA#131]

**Comment by deuszex** [comment]
I'm not sure that's the way to frame a question. 
- Why not Rust? 
- Why does it matter to you? 
- What else? 
You should add those simple things. It is important to phrase it with those things if you don't want answers like: "Just 'cause."
Also the exaggeration with the marks is way too much.

Rust is a good and stable language especially at the low level, it is the usually the fastest behind pure C but with added more modern twists, which makes it ideal for projects like this. Or maybe just the dev likes the language.

**Comment by dtlnor** [comment]
GPT-4：
Rust is a modern systems programming language that has been growing in popularity for several reasons:

1. **Memory Safety**: Rust provides memory safety without needing a garbage collector. This is achieved by a system of ownership with a set of rules that the compiler checks at compile time. No garbage collector is needed, which makes Rust particularly suitable for embedding in other languages, writing low-level code and writing performant code.

2. **Zero-Cost Abstractions**: Rust strives to provide the power of low-level control and high-level convenience, and it does this through a large number of zero-cost abstractions. This means that you can write code that abstracts over details, but that code will run as fast as code written without those abstractions.

3. **Concurrency without Data Races**: Rust has a strong, static type system that prevents data races. It enables highly concurrent and highly safe systems to be developed. This makes Rust a great choice for concurrent programming where safety and performance are paramount.

4. **Interoperability with C**: Rust provides a foreign function interface (FFI) to call C libraries and can be called from C as well. This makes it easier to integrate Rust into existing systems and libraries.

5. **Package Manager**: Rust comes with a built-in package manager called Cargo, which makes it easy to manage dependencies and build your project. Cargo also handles testing and building documentation, making it a comprehensive tool for managing a Rust project.

6. **Great Documentation and Tooling**: Rust has a very strong focus on quality documentation and tooling. The Rust standard library is thoroughly documented, and the official website provides a comprehensive book on Rust. The Rust compiler's error messages are

**Comment by Watynecc** [comment]
> GPT-4： Rust is a modern systems programming language that has been growing in popularity for several reasons:
> 
>     1. **Memory Safety**: Rust provides memory safety without needing a garbage collector. This is achieved by a system of ownership with a set of rules that the compiler checks at compile time. No garbage collector is needed, which makes Rust particularly suitable for embedding in other languages, writing low-level code and writing performant code.
> 
>     2. **Zero-Cost Abstractions**: Rust strives to provide the power of low-level control and high-level convenience, and it does this through a large number of zero-cost abstractions. This means that you can write code that abstracts over details, but that code will run as fast as code written without those abstractions.
> 
>     3. **Concurrency without Data Races**: Rust has a strong, static type system that prevents data races. It enables highly concurrent and highly safe systems to be developed. This makes Rust a great choice for concurrent programming where safety and performance are paramount.
> 
>     4. **Interoperability with C**: Rust provides a foreign function interface (FFI) to call C libraries and can be called from C as well. This makes it easier to integrate Rust into existing systems and libraries.
> 
>     5. **Package Manager**: Rust comes with a built-in package manager called Cargo, which makes it easy to manage dependencies and build your project. Cargo also handles testing and building documentation, making it a comprehensive tool for managing a Rust project.
> 
>     6. **Great Documentation and Tooling**: Rust has a very strong focus on quality documentation and tooling. The Rust standard library is thoroughly documented, and the official website provides a comprehensive book on Rust. The Rust compiler's error messages are

Ain't no way u needed Chatgpt4 for this.

**Comment by 20943204920434** [comment]
> GPT-4： Rust is a modern systems programming language that has been growing in popularity for several reasons:
> 
>     1. **Memory Safety**: Rust provides memory safety without needing a garbage collector. This is achieved by a system of ownership with a set of rules that the compiler checks at compile time. No garbage collector is needed, which makes Rust particularly suitable for embedding in other languages, writing low-level code and writing performant code.
> 
>     2. **Zero-Cost Abstractions**: Rust strives to provide the power of low-level control and high-level convenience, and it does this through a large number of zero-cost abstractions. This means that you can write code that abstracts over details, but that code will run as fast as code written without those abstractions.
> 
>     3. **Concurrency without Data Races**: Rust has a strong, static type system that prevents data races. It enables highly concurrent and highly safe systems to be developed. This makes Rust a great choice for concurrent programming where safety and performance are paramount.
> 
>     4. **Interoperability with C**: Rust provides a foreign function interface (FFI) to call C libraries and can be called from C as well. This makes it easier to integrate Rust into existing systems and libraries.
> 
>     5. **Package Manager**: Rust comes with a built-in package manager called Cargo, which makes it easy to manage dependencies and build your project. Cargo also handles testing and building documentation, making it a comprehensive tool for managing a Rust project.
> 
>     6. **Great Documentation and Tooling**: Rust has a very strong focus on quality documentation and tooling. The Rust standard library is thoroughly documented, and the official website provides a comprehensive book on Rust. The Rust compiler's error messages are

Rust isn't fully "memory safe" as long as you use unsafe{}. Also the syntax is a mess.

**Comment by dtlnor** [comment]
> Ain't no way u needed Chatgpt4 for this.

It's like, if you're asking "Why Use Rust", you should ask GPT, rather than opening an issue. Questions of this nature aren't worth anyone's time to ponder. 😄

**Comment by MathNerd** [comment]
Why does it matter to you which programming language was used? Should matter as an end user.

**Comment by Slayingripper** [comment]
I never knew the end user cared so much for the underlying language used.
