### ISSUE TITLE
Nvidia translation layer ban

### ISSUE THREAD

**Issue by Armada3334** [vosen/ZLUDA#161]
How will the recent EULA change affect ZLUDA development? I hope that ZLUDA will continue to be developed on older versions of CUDA, but I wanted to open a conversation on how to move forward based off of the [EULA changes](https://www.tomshardware.com/pc-components/gpus/nvidia-bans-using-translation-layers-for-cuda-software-to-run-on-other-chips-new-restriction-apparently-targets-zluda-and-some-chinese-gpu-makers)

**Comment by hashelq** [comment]
In fact novideo has been banning running translations layers since 2021. IG this project itself does not go against their EULA and it all sounds dirty. IG running cuda software in no-network sandboxes is ok to not get caught for running cuda apps with zluda.

**Comment by bogan-FMA** [comment]
yes, the EULA include the ban since cuda11.5. wondering any insight from vosen regarding this?

**Comment by AnnoyedDev** [comment]
`Realistically, it's now abandoned and will only possibly receive updates to run workloads I am personally interested in (DLSS).`

**Comment by vosen** [comment]
It always warms my heart to be reminded that of the three GPU vendors, NVIDIA is by far the one that believes in ZLUDA the most.
I expect that CUDA's EULA will affect ZLUDA as much as Windows EULA affects WINE and Intel EULA affects Apple's Rosetta

**Comment by zoobab** [comment]
Such clause is probably illegal under EU Law, the copyright directive allows reverse engineer for interoperability purposes.

**Comment by Armada3334** [comment]
Got some new info:

https://www.tomshardware.com/pc-components/gpus/nvidia-bans-using-translation-layers-for-cuda-software-to-run-on-other-chips-new-restriction-apparently-targets-zluda-and-some-chinese-gpu-makers

**Comment by Armada3334** [comment]
I think this has everything we need to know.
