### ISSUE TITLE
Codility challenge Not 100% correct

### ISSUE THREAD

**Issue by Ahmed0musa00** [vosen/ZLUDA#162]
I got the following challenge on codility:
`int solution(int A, int B);`
that, given two non-negative integers A and B, returns the number of bits set to 1 in the binary representation of the number A * B.
For example, given A = 3 and B = 7 the function should return 3, because the binary
representation of A * B = 3 * 7 = 21 is 10101 and it contains three bits set to 1.
Assume that:
• A and B are integers within the range (0..100,000,000).

My solution was:
`int countSetBits(int n) {
    int count = 0;
    while (n > 0) {
        count += n & 1;
        n >>= 1;
    }
    return count;
}

int solution(int A, int B) {
    // Calculate the product of A and B
    int product = A * B;
    
    // Count the number of set bits in the product
    return countSetBits(product);
}`

In the result I got 50% correctness 6 test cases pass out of 12. I couldn't see the test cases.
I know that an integer overflow here will happened and I should use std::uint64 but that could fail one test case that tests the overflow scenario what about the others?
Anyone has an idea what could be the problem or why I didn't got 100% correctness?

**Comment by vosen** [comment]
Closing because I don't think it is ZLUDA-related
