### ISSUE TITLE
Crush when I running chatglm with zluda

### ISSUE THREAD

**Issue by Oveln** [vosen/ZLUDA#180]
thread '<unnamed>' panicked at zluda_rtc\src\lib.rs:22:16:
[ZLUDA] HIPRTC failed: 6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library\panic_unwind\src\seh.rs:260:8:
Rust panics cannot be copied
stack backtrace:
   0:     0x7ff9d73c7952 - nvrtcGetLoweredName
   1:     0x7ff9d73d54ad - nvrtcGetLoweredName
   2:     0x7ff9d73c63b1 - nvrtcGetLoweredName
   3:     0x7ff9d73c777a - nvrtcGetLoweredName
   4:     0x7ff9d73c8fa9 - nvrtcGetLoweredName
   5:     0x7ff9d73c8c65 - nvrtcGetLoweredName
   6:     0x7ff9d73c94d4 - nvrtcGetLoweredName
   7:     0x7ff9d73c936b - nvrtcGetLoweredName
   8:     0x7ff9d73c7ff9 - nvrtcGetLoweredName
   9:     0x7ff9d73c9072 - nvrtcGetLoweredName
  10:     0x7ff9d73da157 - nvrtcGetLoweredName
  11:     0x7ff9d73ccd5e - nvrtcGetLoweredName
  12:     0x7ffa385822b1 - <unknown>
  13:     0x7ffa38582008 - <unknown>
  14:     0x7ffa38582529 - __ExceptionPtrCurrentException
  15:     0x7ff88db9babd - THPPointer<THPGenerator>::operator bool
  16:     0x7ff88e59fb6b - c10d::PythonCommHook::runHook
  17:     0x7ffa28681080 - <unknown>
  18:     0x7ffa28682715 - _NLG_Return2
  19:     0x7ffa5e873c66 - RtlCaptureContext2
  20:     0x7ff88db9f1f7 - c10::ivalue::Future::devices
  21:     0x7ff9a98fd8a0 - PyObject_VectorcallMethod
  22:     0x7ff9a98c8f2a - PyObject_MakeTpCall
  23:     0x7ff9a9a5438a - PyThread_tss_is_created
  24:     0x7ff9a98fc0b9 - PyObject_Call
  25:     0x7ff9a99302c7 - PyObject_Call
  26:     0x7ff9a9a6e69f - PyThread_tss_is_created
  27:     0x7ff9a98a0691 - PyObject_Vectorcall
  28:     0x7ff9a989fb15 - PyObject_Vectorcall
  29:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
  30:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  31:     0x7ff9a98c1371 - PyDict_GetItemWithError
  32:     0x7ff9a98fc10f - PyObject_Call
  33:     0x7ff9a98fc003 - PyObject_Call
  34:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  35:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  36:     0x7ff9a98c1371 - PyDict_GetItemWithError
  37:     0x7ff9a98fc10f - PyObject_Call
  38:     0x7ff9a98fc003 - PyObject_Call
  39:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  40:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  41:     0x7ff9a9930772 - PyObject_FastCallDictTstate
  42:     0x7ff9a9930e0b - PyObject_Call_Prepend
  43:     0x7ff9a9930d36 - PyDictProxy_New
  44:     0x7ff9a98a0691 - PyObject_Vectorcall
  45:     0x7ff9a989fb15 - PyObject_Vectorcall
  46:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
  47:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  48:     0x7ff9a98c1371 - PyDict_GetItemWithError
  49:     0x7ff9a98fc10f - PyObject_Call
  50:     0x7ff9a98fc003 - PyObject_Call
  51:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  52:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  53:     0x7ff9a98c1371 - PyDict_GetItemWithError
  54:     0x7ff9a98fc10f - PyObject_Call
  55:     0x7ff9a98fc003 - PyObject_Call
  56:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  57:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  58:     0x7ff9a9930772 - PyObject_FastCallDictTstate
  59:     0x7ff9a9930e0b - PyObject_Call_Prepend
  60:     0x7ff9a9930d36 - PyDictProxy_New
  61:     0x7ff9a98a0691 - PyObject_Vectorcall
  62:     0x7ff9a989fb15 - PyObject_Vectorcall
  63:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
  64:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  65:     0x7ff9a98c1371 - PyDict_GetItemWithError
  66:     0x7ff9a98fc10f - PyObject_Call
  67:     0x7ff9a98fc003 - PyObject_Call
  68:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  69:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  70:     0x7ff9a98c1371 - PyDict_GetItemWithError
  71:     0x7ff9a98fc10f - PyObject_Call
  72:     0x7ff9a98fc003 - PyObject_Call
  73:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  74:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  75:     0x7ff9a9930772 - PyObject_FastCallDictTstate
  76:     0x7ff9a9930e0b - PyObject_Call_Prepend
  77:     0x7ff9a9930d36 - PyDictProxy_New
  78:     0x7ff9a98a0691 - PyObject_Vectorcall
  79:     0x7ff9a989fb15 - PyObject_Vectorcall
  80:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
  81:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  82:     0x7ff9a98c1371 - PyDict_GetItemWithError
  83:     0x7ff9a98fc10f - PyObject_Call
  84:     0x7ff9a98fc003 - PyObject_Call
  85:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  86:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  87:     0x7ff9a98c1371 - PyDict_GetItemWithError
  88:     0x7ff9a98fc10f - PyObject_Call
  89:     0x7ff9a98fc003 - PyObject_Call
  90:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
  91:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  92:     0x7ff9a9930772 - PyObject_FastCallDictTstate
  93:     0x7ff9a9930e0b - PyObject_Call_Prepend
  94:     0x7ff9a9930d36 - PyDictProxy_New
  95:     0x7ff9a98a0691 - PyObject_Vectorcall
  96:     0x7ff9a989fb15 - PyObject_Vectorcall
  97:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
  98:     0x7ff9a98bf6ba - PyFunction_Vectorcall
  99:     0x7ff9a98c1371 - PyDict_GetItemWithError
 100:     0x7ff9a98fc10f - PyObject_Call
 101:     0x7ff9a98fc003 - PyObject_Call
 102:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
 103:     0x7ff9a98bf6ba - PyFunction_Vectorcall
 104:     0x7ff9a98c1371 - PyDict_GetItemWithError
 105:     0x7ff9a98fc10f - PyObject_Call
 106:     0x7ff9a98fc003 - PyObject_Call
 107:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
 108:     0x7ff9a98bf6ba - PyFunction_Vectorcall
 109:     0x7ff9a9930772 - PyObject_FastCallDictTstate
 110:     0x7ff9a9930e0b - PyObject_Call_Prepend
 111:     0x7ff9a9930d36 - PyDictProxy_New
 112:     0x7ff9a98fc04a - PyObject_Call
 113:     0x7ff9a98a6b6c - PyEval_EvalFrameDefault
 114:     0x7ff9a99821ad - PyErr_Fetch
 115:     0x7ff9a998206b - PyErr_Fetch
 116:     0x7ff9a98a5f17 - PyEval_EvalFrameDefault
 117:     0x7ff9a98c9bae - PyDict_MergeFromSeq2
 118:     0x7ff9a98a247f - PyEval_EvalFrameDefault
 119:     0x7ff9a99821ad - PyErr_Fetch
 120:     0x7ff9a998206b - PyErr_Fetch
 121:     0x7ff9a98fd141 - Py_CheckFunctionResult
 122:     0x7ff9a989fbc1 - PyObject_Vectorcall
 123:     0x7ff9a989fb15 - PyObject_Vectorcall
 124:     0x7ff9a98a1ba7 - PyEval_EvalFrameDefault
 125:     0x7ff9a98c9bae - PyDict_MergeFromSeq2
 126:     0x7ff9a98a247f - PyEval_EvalFrameDefault
 127:     0x7ff9a9930996 - PyType_CalculateMetaclass
 128:     0x7ff9a99314a1 - PyEval_EvalCode
 129:     0x7ff9a991bfc8 - PyUnicode_GetLength
 130:     0x7ff9a991cf6c - PyDict_GetItemStringWithError
 131:     0x7ff9a9962528 - PyImport_FixupExtensionObject
 132:     0x7ff9a9962122 - PyRun_SimpleFileObject
 133:     0x7ff9a9962944 - PyRun_AnyFileObject
 134:     0x7ff9a9962fae - Py_Exit
 135:     0x7ff9a9963053 - Py_Exit
 136:     0x7ff9a9963d43 - Py_RunMain
 137:     0x7ff9a9963af5 - Py_RunMain
 138:     0x7ff9a99632d1 - Py_Main
 139:     0x7ff7d9b01230 - <unknown>
 140:     0x7ffa5e2a257d - BaseThreadInitThunk
 141:     0x7ffa5e82aa58 - RtlUserThreadStart

**Comment by vosen** [comment]
Hi, `zluda_rtc\src\lib.rs` is not part of the ZLUDA codebase. I'm guessing you are using a fork of ZLUDA. In this case, please contact fork's author for support
