### ISSUE TITLE
What's the difference between CuPBoP-AMD and ZLUDA？

### ISSUE THREAD

**Issue by eatcosmos** [vosen/ZLUDA#182]
What's the difference between CuPBoP-AMD and ZLUDA？

https://github.com/gthparch/CuPBoP-AMD
and
https://github.com/vosen/ZLUDA

**Comment by vosen** [comment]
Broadly speaking, CuPBoP is a solution for developers, ZLUDA is a solution for users. CuPBoP works at the source code level: with CuPBoP compiler you recompile the CUDA source code to target AMD GPU. ZLUDA works at the binary level: you run the already compiled CUDA application under ZLUDA.

* ZLUDA can run closed-source applications without developers intervention (or even knowledge)
* CuPBoP theoretically has the potential for better performance
* ZLUDA is more complete at the moment
