### ISSUE TITLE
Blender display Nvidia smi is not recognized as an internal or external command, an executable program or a batch file.

### ISSUE THREAD

**Issue by gioxyer** [vosen/ZLUDA#213]
“nvidia-smi” is not recognized as an internal or external command, an executable program or a batch file.
![image](https://github.com/vosen/ZLUDA/assets/161426313/3e18d149-80a3-4f84-a73a-459c9bcfbf73)

**Comment by gioxyer** [comment]
ZLUDA with Blender 4.1 compatibility version used
[zluda.zip](https://github.com/vosen/ZLUDA/files/15104815/zluda.zip)

**Comment by wfjsw** [comment]
This is not a zluda issue nor blender; it is a ComfyUI-BlenderAI-node issue.

**Comment by vosen** [comment]
Does it blocks some functionality?
`nvidia-smi` is used for querying system GPU properties like GPU clock, memory clock, brand of VRAM, etc. `nvidia-smi` missing should not be a problem

**Comment by gioxyer** [comment]
No problem, Zluda works well, only display the error

**Comment by vosen** [comment]
Ok, I'm closing it then
