### ISSUE TITLE
ZLUDA CUStream error with heavy Blender projects [CU_STREAM_NON_BLOCKING]

### ISSUE THREAD

**Issue by gioxyer** [vosen/ZLUDA#223]
With heavy project cuda failed to load viewport render

CMD display error:
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html

Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)
Out of memory in cuStreamCreate(&cuda_stream_, CU_STREAM_NON_BLOCKING) (C:\Users\blender\git\blender-v410\blender.git\intern\cycles\device\cuda\queue.cpp:21)

Issue with ZLUDA memory
![Out of memory cuda v2](https://github.com/vosen/ZLUDA/assets/161426313/167ffff1-2fd3-44c4-bdfe-ea1e4b269fce)

Viewport doesn't loading render
![Out of memory cuda v1](https://github.com/vosen/ZLUDA/assets/161426313/b5016ec6-76a9-43b2-8bc9-ed4e32779b3a)

**Comment by vosen** [comment]
What happens if you render from command line?
```
blender.exe -d --debug-cycles -noaudio --enable-autoexec -b <BLEND_FILE> -x 1 -F PNG -f 1 -- --cycles-device CUDA
```
Can you send me the scene?

**Comment by gioxyer** [comment]
This should be after blender.exe?  -d --debug-cycles -noaudio --enable-autoexec -b <BLEND_FILE> -x 1 -F PNG -f 1 -- --cycles-device CUDA

[https://we.tl/t-N1u2opZDCx](https://we.tl/t-N1u2opZDCx?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

**Comment by gioxyer** [comment]
[blender_debug_output.txt](https://github.com/vosen/ZLUDA/files/15212674/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/vosen/ZLUDA/files/15212675/blender_system_info.txt)

**Comment by vosen** [comment]
I've tried the scene you've attached. I have 64 GB RAM and I'm consistently getting blender crashes with out-of-memory with all GPU backends: CUDA-ZLUDA, CUDA and HIP. Maybe you are running of memory too (errors you are getting also suggest this)?

**Comment by gioxyer** [comment]
Yes, I tried a few hours ago, I have same problem, after 3 crashes, the fourth time it display "Out of Memory"
![image](https://github.com/vosen/ZLUDA/assets/161426313/f4f04599-eb42-455e-b6bf-8eb496550c54)

**Comment by vosen** [comment]
I'm closing it, since it does not seem to be related to ZLUDA, but rather Blender running out of RAM.
