### ISSUE TITLE
nvcuda.dll hipDeviceSetLimit Error

### ISSUE THREAD

**Issue by LeonardoIz** [vosen/ZLUDA#249]
I tried to run ZLUDA and it gives me this error, I'm using Windows 10:
The procedure entry point hipDeviceSetLimit could not be found in the dynamic link library D:\Apps\ZLUDA\nvcuda.dll
![image](https://github.com/vosen/ZLUDA/assets/68020110/22a04787-c5cc-46ed-8245-626ca422e38b)

**Comment by AnthonyMx7** [comment]
Having the same issue.

**Comment by John10v10** [comment]
same, can anyone please help?

**Comment by arcadeus** [comment]
same ... ((((

**Comment by xxTVOJAMAMAxx** [comment]
im having the same issue

**Comment by xxTVOJAMAMAxx** [comment]
I had the same exact error message pop-up
Tried a lot of setup options, installing hip, python, ROCm, visual script, SDnext, git
Tried putting nvcuda.dll in blender folder and it still didn't work
I was using Amernimez drivers for my RX 580
Now i reinstalled driver to Adrenaline 24.7.1

Now i can run Blender, didn't work to work 1st and 2nd time, and it defaulted to HIP cycles (for some reason) which didn't work, and after changing to CUDA everything works fine! Now my GPU Compute 0 in task manager is at 100%

I can say this has been solved for me! 
I hope this helps anyone 
And i have to give huge thanks to VOSEN, thank you a lot for your work, its amazing!

**Comment by vosen** [comment]
Usually this happens because you have an old version of Adrenalin driver.
Closing because it no longer applies
