### ISSUE TITLE
< was unexpected at this time.

### ISSUE THREAD

**Issue by h7hc** [vosen/ZLUDA#254]
![image](https://github.com/user-attachments/assets/15dee7d9-186a-4989-a29f-d75e4f1c2294)

Everytime I paste the command "<ZLUDA_DIRECTORY>\zluda.exe -- <APPLICATION> <APPLICATION_ARGUMENTS>" nothing happens and it says "< was unexpected at this time."

after a few tries, I figured out that "<" in "<APPLICATION_ARGUMENTS>" was the problem. But when I delete it I get another error.

![image](https://github.com/user-attachments/assets/74e3981a-f5a6-44d8-9459-caab81134cb8)

"The syntax of the command is incorrect."

**Comment by lshqqytiger** [comment]
Replace `<ZLUDA_DIRECTORY>` with where `zluda.exe` is.
Replace `<APPLICATION>` with the path to an application that you want to run with ZLUDA.
Replace `<APPLICATION_ARGUMENTS>` with the list of arguments you want to pass to the application.

**Comment by h7hc** [comment]
> Replace `<ZLUDA_DIRECTORY>` with where `zluda.exe` is. Replace `<APPLICATION>` with the path to an application that you want to run with ZLUDA. Replace `<APPLICATION_ARGUMENTS>` with the list of arguments you want to pass to the application.

This makes a lot of sense, thanks for helping.
