### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by raksonraks** [vosen/ZLUDA#273]
This is the issue i am experiencing
![WhatsApp Image 2024-09-17 at 01 30 34](https://github.com/user-attachments/assets/1155d04c-5a06-4ab8-ab69-af8c2bac7d96)

This is the last driver version that could be installed for this graphics card
![WhatsApp Image 2024-09-17 at 01 33 26](https://github.com/user-attachments/assets/fd8f7acc-5827-4ac4-ad38-b34787b2de8c)

Could you help.

![WhatsApp Image 2024-09-17 at 01 34 33](https://github.com/user-attachments/assets/df07683f-0eb4-4cc1-af99-438f661d9e60)

**Comment by vosen** [comment]
Try updating the Adrenalin driver. That version is quite old and hipGraphCreate is a relatively recent driver addition

**Comment by raksonraks** [comment]
This is the latest of the Adrenalin driver, but could i download a newer version perchance.
https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-600-500-400/radeon-500-series/radeon-530.html

**Comment by raksonraks** [comment]
I have updated my Adrenaline driver to a newer version, but its unofficial, i had to go to such means because my gpu is a legacy one and its no longer getting driver updates since 2022.
https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-600-500-400/radeon-500-series/radeon-530.html
Here is the unofficial driver i have downloaded.
https://sourceforge.net/projects/radeon-id-distribution/files/
I installed the driver following this tutorial, it was posted in 2021 but it still works.
https://forums.guru3d.com/threads/radeon-id-community-driver-hybrid-release-nebula-23-11-1-whql.436611/
Here is a screenshot of my amd radeon app.
Before:
![image](https://github.com/user-attachments/assets/94f6d4f0-cbe0-4b7b-820f-447643fe310b)
After:
![WhatsApp Image 2024-09-17 at 14 55 09](https://github.com/user-attachments/assets/654061bb-9177-4629-a286-b582ca41f59f)

Only the driver version got updated ,but the software one didint, also i noticed a slight chnage in my amd radeon software settings.

I would like to provide if needed, can you help?

**Comment by vosen** [comment]
Sorry, I'm closing the issue then. If there is no newer Adrenalin driver available for your hardware, then there's nothing that can be done in ZLUDA
