### ISSUE TITLE
[Question] ZLUDA to run CUDA on Nvidia GPUs?

### ISSUE THREAD

**Issue by TheFloatingBrain** [vosen/ZLUDA#274]
Hi this may seem a bit cursed but I am tired of the proprietary driver on linux (its maintenance, its not auditable, and it taints my kernel), I have been looking into just using mesa opencl but [I am having trouble with the opencl driver right now](https://unix.stackexchange.com/questions/783578/nouveu-driver-not-working-fedora-40), I know `ucx` supports CUDA (looking to use OpenMPI for something), so I was curious, can I use ZLUDA to run CUDA on an Nvidia GPU on Linux? And if so, how?

**Comment by vosen** [comment]
ZLUDA can't really help you there, but there is a project attempting this here: https://github.com/mikex86/LibreCuda

**Comment by TheFloatingBrain** [comment]
Thanks for answering my question
