### ISSUE TITLE
Support for Github actions artifacts?

### ISSUE THREAD

**Issue by oscarbg** [vosen/ZLUDA#32]
Hi,
just wanting to test latest code from master supporting latest cuda runtime on Windows (https://github.com/vosen/ZLUDA/commit/5cd9a5fbc4b92c58a1db6f205559e690af30481b)..
Lazy to build project just to do a quick test and seems github actions support currently lacks support for artifacts..
https://github.com/vosen/ZLUDA/actions/runs/472515955
I'm mainly interested on seeing support for Windows builds artifacts (so having the resulting zluda.dll but better if Linux zluda.so is built also)..
thanks..

**Comment by vosen** [comment]
Yes, this is important. First, I want to have a more robust way to run Windows applications with ZLUDA (currently it requires too much manual intervention) and finish up GeekBench support. Then I'll be looking into improving CI to have a Windows build and to upload artifacts.

**Comment by oscarbg** [comment]
nice to hear! thanks..

**Comment by vosen** [comment]
Should work with #39

**Comment by oscarbg** [comment]
thanks! 
will test soon and report..
but upon quick test using zluda_with tool on Windows I get:
zluda_with -- CUDA-Z-0.11.259-SVN-64bit.exe
I get error missing zluda_redirect.dll in the Windows artifact..

**Comment by oscarbg** [comment]
EDIT: in addition to zluda_with zluda_redirect.dll issue I also see no 32bit Windows nvcuda.dll present in artifact..
I was going to test and old CUDA-Z:
CUDA-Z-0.10.251-32bit.exe

**Comment by vosen** [comment]
Ooops, zluda_redirect.dll is now included.
As for 32bits there's no simple way forward. ZLUDA relies on Level 0 API and it's 64bit only with no plans for 32bit. There's a potential path to 32bit, but it's not simple and has some limitations (more discussion here: #31).

**Comment by oscarbg** [comment]
thanks..
yes now CUDA-Z works.. so closing issue..
didn't know L0 was 64 bit only..
