### ISSUE TITLE
cudaMemcpy & cudaMallocHost return CUDA error 71 operation not supported

### ISSUE THREAD

**Issue by VitaliiGitHub** [vosen/ZLUDA#46]
Hello All,
I downloaded last Release from GitHub. And tryed to run simple application with CUDA using "zluda_with.exe -- test_app.exe" and in process get next errors: for calls cudaMallocHost/cudaMemcpy: "CUDA error 71 operation not supported". I can replace the cudaMallocHost method with other host methods such as malloc/free and new/delete. But there is no way to transfer data to the GPU and back without cudaMemcpy. How to deal with this?

**Comment by vosen** [comment]
Closing this as no longer relevant.
Feel free to reopen if it still appplies to the new version
