### ISSUE TITLE
Question about the cuGetExportTable implementation

### ISSUE THREAD

**Issue by xzhangxa** [vosen/ZLUDA#47]
Hello @vosen ,

I'm learning from your code and want to make it work with Tiger Lake Xe GPU and CUDA 11.3 programs. ZLUDA currently can work with pre-built CUDA 10.x program (for example the official vectorAdd sample), but cannot work with the same source code if it is built with CUDA 11.3. When debugging the problem it seems to me the reason may be the private `cuGetExportTable` function and the vtable/callback it returns.

Since `cuGetExportTable` info is undocumented by NVIDIA, could you let me know how you knew the detail and implemented this part (zluda/src/impl/export_table.rs)? I'm appreciated if you could share how you did it before, thank you.

**Comment by Wongboo** [comment]
[this discussion](https://forums.developer.nvidia.com/t/cudagetexporttable-a-total-hack/20226) might help?

**Comment by vosen** [comment]
Here's a breakdown of all known (by ZLUDA) functions from the cuGetExportTable:
https://github.com/vosen/ZLUDA/blob/1b9ba2b2333746c5e2b05a2bf24fa6ec3828dcdf/zluda_dark_api/src/lib.rs#L197
The grammer is:
```
[GUID]
=> INTERFACE_NAME[NUMBER_OF_FUNCTIONS_IN_THE_INTERFACE] {
    FUNCTION_INDEX =>FUNCTION_SIGNATURE
}
```

Closing, but feel free to open a new issue or email me if you have more questions
