### ISSUE TITLE
[low prio] [Question] ZLUDA support for open-source `nouveau` driver

### ISSUE THREAD

**Issue by stradicat** [vosen/ZLUDA#48]
Hello,

I came across this project a couple of weeks ago, and I was wondering if ZLUDA can work with the open-source `nouveau` driver on older Tesla GPUs, as the driver supports them well and the chip works with OpenCL.

However, only OpenCL 1.2 is supported.
What are ZLUDA's OpenCL requirements?

**Comment by vosen** [comment]
ZLUDA can't be built on top of pure OpenCL. Perhaps on OpenCL + a lot of OpenCL extensions (unified memory, bindless images, virtual calls, various instructions, denormals, many others).
Could ZLUDA be built on top of whatever is underlying nouveau's code? Probably yes
