### ISSUE TITLE
new version of nvcuda.dll?

### ISSUE THREAD

**Issue by meokey** [vosen/ZLUDA#50]
I'm trying to import torch and run torch.cuda.get_device_name(0), it throws the following error message：
RuntimeError: The NVIDIA driver on your system is too old (found version 2147483647). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

I'm wondering it could be the version of nvcuda.dll comes with zluda is too old, so I replace the dll with newer version (NVIDIA CUDA 10.2.108 driver v. 26.21.14.4166), however, it gives another error:
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

any advise is appreciated. Thanks.

**Comment by Li-Xiao-Yu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vosen** [comment]
Closing because no longer relevant.
Feel free to open a new issue if it applies to the new version
