### ISSUE TITLE
How to run Python scripts using ZLUDA ?

### ISSUE THREAD

**Issue by haow85** [vosen/ZLUDA#51]
How do I use ZLUDA to run Python code with CUDA support on Windows ? Looks like zluda_with.exe only supports exe files on Windows.

**Comment by Li-Xiao-Yu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Li-Xiao-Yu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by koast18** [comment]
You can just use it to run python.exe and pass your script as the parameter of it,have a try

**Comment by Li-Xiao-Yu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vosen** [comment]
Closing because no longer relevant.
Feel free to open a new issue if it applies to the new version
