### ISSUE TITLE
Is it possible to run Stable Diffusion AUTOMATIC1111 on Intel Arc A--- GPU?

### ISSUE THREAD

**Issue by Constanted313** [vosen/ZLUDA#52]
Perhaps my question is a bit stupid, but it seems to me an interesting idea to launch this version of Stable Diffusion, which is based on the use of CUDA cores of the video card. At the moment I am using 1050 Ti for it, but I would like to test the Intel Arc A380, which is also in the computer. When trying to run stable diffusion with 1050 Ti disabled, Pytorch returns to the console what is shown in the attached picture (https://imgur.com/a/Kl2kAvl), is there a way around this or does it refer to "Some applications use CUDA in ways that make it incompatible with ZLUDA"?

**Comment by Li-Xiao-Yu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by TheWonderfulTartiflette** [comment]
@lxygoodjob You still haven't answered after 3 months of "vacation", me too I want to know if Zluda works with Intel Arc GPUs

**Comment by Constanted313** [comment]
> @lxygoodjob You still haven't answered after 3 months of "vacation", me too I want to know if Zluda works with Intel Arc GPUs

I think that this is possible only if this technology is correctly "implanted" into the AUTOMATIC 1111 Stable Diffusion itself. But now there is already one version that can work with Intel Arc, albeit very poorly due to problems with the use of video memory (https://github.com/Aloereed/stable-diffusion-webui-arc-directml)

**Comment by Constanted313** [comment]
> > @lxygoodjob You still haven't answered after 3 months of "vacation", me too I want to know if Zluda works with Intel Arc GPUs
> 
> I think that this is possible only if this technology is correctly "implanted" into the AUTOMATIC 1111 Stable Diffusion itself. But now there is already one version that can work with Intel Arc, albeit very poorly due to problems with the use of video memory (https://github.com/Aloereed/stable-diffusion-webui-arc-directml)

https://github.com/openvinotoolkit/stable-diffusion-webui/wiki/Installation-on-Intel-Silicon

**Comment by vosen** [comment]
Closing because no longer relevant.
Feel free to open a new issue if it applies to the new version
