### ISSUE TITLE
An error occurred while displaying "D: \ zluda \ ZLUDA \ target \ release \ zluda redirect.Dll  The dynamic link library (DLL) initialization routine failed"

### ISSUE THREAD

**Issue by linvoes** [vosen/ZLUDA#55]
An error occurred while displaying "D: \ zluda \ ZLUDA \ target \ release \ zluda redirect.Dll  The dynamic link library (DLL) initialization routine failed"

**Comment by vosen** [comment]
Might be the case of trying to run a 32 bit application, which ZLUDA does not support. Anyway, closing because no longer relevant.
Feel free to open a new issue if it applies to the new version
