### ISSUE TITLE
Take my money

### ISSUE THREAD

**Issue by Baigle** [vosen/ZLUDA#57]
You heard me, so where can I contribute and would that help you or the project to continue long term?

**Comment by IanSzot** [comment]
FAQ says it's abandoned due to lack of interest from Intel and AMD unfortunately

**Comment by Strikoder** [comment]
For real, this project need to be supported

**Comment by sorasoras** [comment]
Same

**Comment by IntrovertedFL** [comment]
Willing to donate towards this as well.

**Comment by ZachAR3** [comment]
> FAQ says it's abandoned due to lack of interest from Intel and AMD unfortunately

Abandoned as in officially since Intel and AMD were funding full time dev on it previously, doesn't mean it won't still be worked on especially given the interest.

**Comment by userbox020** [comment]
this project is open source, we have the code, we can code and find us time to improve and keep developing if we really interested. @Baigle if you want to contribute you can hire some engineers on any freelanzer site like upwork, fivver or even here bro.

**Comment by Lamonz88** [comment]
I'd say we need to  organise a public donations fund and then hire a developer..

**Comment by Lamonz88** [comment]
> You heard me, so where can I contribute and would that help you or the project to continue long term?

I'd also like to contribute in some sort of way .

**Comment by wiki-me** [comment]
It is possible to set up bounties in [polar](https://polar.sh) or [algora](https://console.algora.io/) , bounties might show there is enough real world interest to set up a more permanent funding stream using something like liberapay or patreon.

**Comment by Kreijstal** [comment]
> > It is possible to set up bounties in [polar](https://polar.sh) or [algora](https://console.algora.io/) , bounties might show there is enough real world interest to set up a more permanent funding stream using something like liberapay or patreon.
> 
> People have already improved on the original code for use in webui stable diffusion. You can check out SD.Next for the new binaries under the Windows Zluda tutorial. Things seem to be coming along naturally, fortunately. I don't think the bounty is necessary anymore, unless the original dev shows he's willing to take it. Which for now, is not the case. Please correct me if I'm wrong @vosen.

can you show where their version of zluda is?

**Comment by vosen** [comment]
@V6ser right now I'm not considering crowdsourcing, I'm trying to find a commercial backer for ZLUDA

**Comment by wiki-me** [comment]
> can you show where their version of zluda is?

I didn't find it using the project he mentioned, but there is [this](https://github.com/lshqqytiger/ZLUDA) fork which seems more active (see [1](https://github.com/vosen/ZLUDA/graphs/contributors?from=2024-01-24&to=2024-04-09&type=c) and [2](https://github.com/lshqqytiger/ZLUDA/graphs/contributors?from=2024-01-28&to=2024-04-09&type=c)) , maybe it will be better to talk to the author of the fork about crowdfunding.

> @V6ser right now I'm not considering crowdsourcing, I'm trying to find a commercial backer for ZLUDA

I doubt you will find a single sponsor that will pay something like a 100K salary for this, setting up some sort of fundraising process that incentivize multiple business to sponsor (by providing support, or "advertising" by linking to the company on the website/readme/docs) , like [vue.js](https://github.com/sponsors/yyx990803) or [blender](https://fund.blender.org/) does seems like a better bet IMO

**Comment by Kreijstal** [comment]
> > can you show where their version of zluda is?
> 
> I didn't find it using the project he mentioned, but there is [this](https://github.com/lshqqytiger/ZLUDA) fork which seems more active (see [1](https://github.com/vosen/ZLUDA/graphs/contributors?from=2024-01-24&to=2024-04-09&type=c) and [2](https://github.com/lshqqytiger/ZLUDA/graphs/contributors?from=2024-01-28&to=2024-04-09&type=c)) , maybe it will be better to talk to the author of the fork about crowdfunding.
> 
> > @V6ser right now I'm not considering crowdsourcing, I'm trying to find a commercial backer for ZLUDA
> 
> I doubt you will find a single sponsor that will pay something like a 100K salary for this, setting up some sort of fundraising process that incentivize multiple business to sponsor (by providing support, or "advertising" by linking to the company on the website/readme/docs) , like [vue.js](https://github.com/sponsors/yyx990803) or [blender](https://fund.blender.org/) does seems like a better bet IMO

Thank you so much!

**Comment by vosen** [comment]
Hi, I know it took some time, but ZLUDA's development is now funder. See news here: https://vosen.github.io/ZLUDA/blog/zludas-third-life/

**Comment by Kreijstal** [comment]
bluesisters we won
