### ISSUE TITLE
ZLUDA for Apple M1 and later GPUs?

### ISSUE THREAD

**Issue by alexmyczko** [vosen/ZLUDA#58]
Not looked at the details, but could that work? Can provide an ssh access to http://bananas.debian.net

Also does this make nvtop and gpu-burn run on AMD GPUs?

**Comment by Nindaleth** [comment]
ZLUDA is AMD-only - from the readme:

> ZLUDA is built purely on ROCm/HIP

nvtop already runs on AMD GPUs without any CUDA or ZLUDA.
