### ISSUE TITLE
What are the basic requirements?

### ISSUE THREAD

**Issue by zaskokus** [vosen/ZLUDA#60]
Having issues running it under latest ArchLinux. What are the required packages, binaries, libraries except the release file.
```
~$ PATH="$PATH:/opt/rocm/bin" LD_LIBRARY_PATH="/home/asd/tmp/zluda/zluda/:$LD_LIBRARY_PATH" ./Downloads/CUDA-Z-0.10.251-64bit.run 
CUDA-Z Started!
Can't load CUDA driver.
CUDA Present: 0
```

**Comment by NXij** [comment]
See the readme
> (Linux only) ROCm 5.7+ (not ROCm 6)

ROCm is version 6 in arch repos and hence wont work.
