### ISSUE TITLE
PhysX

### ISSUE THREAD

**Issue by liandris** [vosen/ZLUDA#72]
See the https://github.com/vosen/ZLUDA/discussions/31 from 3 years ago.

Basically, what looks to be main obstacles (maybe they are parts of the same underlying issue) are:

>ZLUDA launcher (`zluda.exe`) does not support 32 bit processes.

>ZLUDA does not support CUDA gaming workloads (PhysX or DLSS)

And I'm wondering if something can be done in the future about this because this tool might be in a great shape to be able to preserve older games in a way, and maybe also unlock their features on handheld platforms like Steam Deck.

**Comment by vosen** [comment]
I'm closing this issue because it's more of a sort long term project that's better suited for discussion already in #31.
I'll post my thoughts there
