### ISSUE TITLE
Have both Blue and Red Teams

### ISSUE THREAD

**Issue by erkinalp** [vosen/ZLUDA#86]
add the intel gpu support back

**Comment by Apocrathia** [comment]
There are already several forks that have diverged before the red team update and have continued building on the Intel functionality. https://github.com/vosen/ZLUDA/network

**Comment by Kreijstal** [comment]
> I doubt he couldn't without spend consider amount of time.

just wrap previous code in a if macro, whats the problem :)

**Comment by vosen** [comment]
I'm closing this as duplicate. Feel free to continue discussion in #85
