### ISSUE TITLE
Query : Is intel support removed ? Can it still work on intel descrete GPUs ?

### ISSUE THREAD

**Issue by vinaykumarintel** [vosen/ZLUDA#93]

**Comment by vinaykumarintel** [comment]
We are planning to try it out on intel Flex* Data Center GPUs.
will this work on it ?

**Comment by eadmaster** [comment]
https://github.com/vosen/ZLUDA/issues/86

**Comment by vosen** [comment]
I'm closing this as duplicate. Feel free to continue discussion in #85
