### ISSUE TITLE
Any possible alternatives to hipBLASLt?

### ISSUE THREAD

**Issue by jin-eld** [vosen/ZLUDA#97]
Hi,

I'm really excited about this awesome project, however if I understand correctly only people with gfx90a and gfx94x based hardware can actually use it? Is far as I can tell ZLUDA is linking vs hipBLASLt, which only supports the above mentioned cards, everyone else is out of luck.

I am not an expert on the ROCm ecosystem yet, so perhaps you could provide some insight - are there alternative libraries which would work on other hardware and which could be used instead? How much of a hard requirement is hipBLASLt (say, if there was an option to make it a compile time option)?

Kind regards,
Jin

**Comment by vosen** [comment]
Not sure what you mean. For building ZLUDA you don't need even need a GPU. During run time if an application does not use cuBLASLt then hipBLASLt does not get loaded.
As for hipBLASLt alternatives, I don't know

**Comment by jin-eld** [comment]
Hmm, I was running the cargo build as described in the docs, it seemed to build some native (-sys) stuff and threw a link error, because it did not find hipBLASLt on my system, which was correct as I did not have it installed. I assumed that it's a must have dependency, hence my question, but I think I understand better now - what is actually being loaded and used will be decided during runtime, depending on the application.
Thank you for the clarification!

As for hipBLASLt alternatives - I guess I need to do my own research then, I am one of the unlucky MI25 gfx9000 owners.
