### ISSUE TITLE
Windows Defender flagged zluda.exe as a Trojan

### ISSUE THREAD

**Issue by R-N** [vosen/ZLUDA#98]
<details>
<summary>Windows Defender flagged zluda.exe (Version 3) as a Trojan:Win32/Wacatac.B!ml</summary>

![image](https://github.com/vosen/ZLUDA/assets/1442761/c3a104d4-a798-4c03-b672-37034be96c1e)
</details>

[3 flags on VirusTotal](https://www.virustotal.com/gui/file/8c06c8a80000bdf1f3ce2b58c5a577a7b84393505b5aedbdbd8cc940b64820dc)

It should be a false positive, right?

**Comment by vosen** [comment]
Yes, I've ran a scan on my machine and it came back clean.
Detections with `!ml` suffix come from Defender machine learning mode.
It looks to me like a case of "6 fingers" machine learning virus detection, but if you are still worried then build from sources

**Comment by DGdev91** [comment]
Yes, it's a known problem, it's written in the readme

```
Antivirus flags ZLUDA as malware.

ZLUDA launcher (zluda.exe) uses some of the techniques used by malware, but for good. zluda.exe hijacks the process and redirects all uses of the original NVIDIA's CUDA libraries to use ZLUDA's CUDA instead.

Don't use zluda.exe with games that use anti-cheat. ZLUDA does not support CUDA gaming workloads (PhysX or DLSS) and anti-cheat might mistake zluda.exe for a malware or a cheat.

```

**Comment by R-N** [comment]
I see. Thank you

**Comment by radu1006** [comment]
Also Bitdefender blocks it as malware.
